[package]
name = "preen-core"
version = "0.1.0"
edition = "2024"
description = "Core logic and data models for the Preen system cleaner and optimizer."
license = "MIT"
repository = "https://github.com/Preen-rs/preen.git"
readme = "README.md"

[dependencies]
chrono = { version = "0.4.38", features = ["serde", "std"] } # For timestamping history entries
tokio = { version = "1", features = ["full"] } # For async runtime and scheduling
tokio-stream = "0.1" # For async streams
async-trait = "0.1" # For async traits
uuid = { version = "1.0", features = ["v4", "fast-rng", "macro-diagnostics"] } # For generating unique IDs
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
tempfile = "3.10"
thiserror = "1.0"
semver = "1.0"
serde_json = "1.0"
rust-i18n = "3"

[dev-dependencies]
serde_yaml = "0.9"
