use async_trait::async_trait;
use chrono::{DateTime, Duration, Local};
use preen_core::error::CoreError;
use preen_core::metrics::{MetricsSink, NoopMetrics};
use preen_core::store::{ItemRecord, ScanStorePort};
use preen_core::{
    CleanableItem, FileSystemPort, ScanResult,
    config::AppConfig,
    rules::{ScanRule, ScanStrategy},
};
use rayon::prelude::*;
use regex::Regex;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use thiserror::Error;
#[cfg(all(unix, not(target_os = "macos")))]
use trash::TrashItem;
use trash::{self};
use uuid::Uuid;
use walkdir::{DirEntry, WalkDir};

pub mod action_executor;
pub mod store;
#[cfg(all(unix, not(target_os = "macos")))]
const LINUX_UNDO_PREFIX: &str = "linux-trash";

// --- OS-specific FileSystemPort Implementation ---

pub struct OsFileSystemAdapter {
    store: Arc<dyn ScanStorePort>,
    metrics: Arc<dyn MetricsSink>,
}

#[derive(Debug, Error)]
pub enum OsError {
    #[error("io error at {path}: {source}")]
    Io {
        path: String,
        source: std::io::Error,
    },
    #[error("permission denied: {path}")]
    PermissionDenied { path: String },
    #[error("invalid path: {path}")]
    InvalidPath { path: String },
    #[error("trash error at {path}: {source}")]
    Trash { path: String, source: trash::Error },
    #[error("store error: {message}")]
    Store { message: String },
}

impl OsFileSystemAdapter {
    #[cfg(all(unix, not(target_os = "macos")))]
    fn encode_linux_undo_info(item_id: &str, original_path: &Path) -> String {
        format!(
            "{LINUX_UNDO_PREFIX}\0v1\0{item_id}\0{}",
            original_path.to_string_lossy()
        )
    }

    #[cfg(all(unix, not(target_os = "macos")))]
    fn decode_linux_undo_original_path(raw: &str) -> PathBuf {
        let mut parts = raw.splitn(4, '\0');
        let prefix = parts.next();
        let version = parts.next();
        let _item_id = parts.next();
        let path = parts.next();
        if prefix == Some(LINUX_UNDO_PREFIX) && version == Some("v1") {
            if let Some(path) = path {
                return PathBuf::from(path);
            }
        }
        PathBuf::from(raw)
    }

    pub fn get_os_specific_rules() -> Vec<ScanRule> {
        let mut rules = Vec::new();
        if cfg!(target_os = "macos") {
            rules.push(ScanRule {
                id: "macos-caches".to_string(),
                name: "macOS Caches".to_string(),
                category: preen_core::ItemCategory::Cache,
                path_pattern: "~/Library/Caches".to_string(),
                strategy: ScanStrategy::Recursive,
                description: "Temporary files and caches generated by macOS applications."
                    .to_string(),
            });
            rules.push(ScanRule {
                id: "xcode-derived-data".to_string(),
                name: "Xcode Derived Data".to_string(),
                category: preen_core::ItemCategory::TemporaryFiles,
                path_pattern: "~/Library/Developer/Xcode/DerivedData".to_string(),
                strategy: ScanStrategy::Recursive,
                description: "Temporary build files and indexes generated by Xcode.".to_string(),
            });
        } else if cfg!(target_os = "linux") {
            rules.push(ScanRule {
                id: "linux-tmp".to_string(),
                name: "Linux Temporary Files".to_string(),
                category: preen_core::ItemCategory::TemporaryFiles,
                path_pattern: "/tmp".to_string(),
                strategy: ScanStrategy::Recursive,
                description: "System-wide temporary files on Linux.".to_string(),
            });
            rules.push(ScanRule {
                id: "linux-user-cache".to_string(),
                name: "Linux User Caches".to_string(),
                category: preen_core::ItemCategory::Cache,
                path_pattern: "~/.cache".to_string(),
                strategy: ScanStrategy::Recursive,
                description: "User-specific cache files on Linux.".to_string(),
            });
        }
        rules
    }

    pub fn new(store: Arc<dyn ScanStorePort>) -> Self {
        let metrics = match std::env::var("PREEN_METRICS").ok().as_deref() {
            Some("stdout") => Arc::new(preen_core::metrics::StdoutMetrics) as Arc<dyn MetricsSink>,
            _ => Arc::new(NoopMetrics),
        };
        OsFileSystemAdapter { store, metrics }
    }

    pub fn with_metrics(store: Arc<dyn ScanStorePort>, metrics: Arc<dyn MetricsSink>) -> Self {
        OsFileSystemAdapter { store, metrics }
    }

    fn is_system_path(path: &Path) -> bool {
        let blocked = [
            "/usr",
            "/var",
            "/System",
            "/Library/Extensions",
            "/bin",
            "/sbin",
        ];
        blocked.iter().any(|prefix| path.starts_with(prefix))
    }

    // Helper function to check if a path should be ignored
    fn is_ignored(&self, path: &Path, config: &AppConfig) -> bool {
        if !config.scan_system_dirs && Self::is_system_path(path) {
            return true;
        }
        if !config.allowlist.is_empty() {
            let allowed = config.allowlist.iter().any(|allow| {
                let expanded = shellexpand::tilde(allow).to_string();
                path.to_string_lossy().starts_with(&expanded)
            });
            if !allowed {
                return true;
            }
        }
        config.ignore_list.iter().any(|ignore_pattern| {
            let expanded_pattern = shellexpand::tilde(ignore_pattern).to_string();
            if let Ok(pattern) = glob::Pattern::new(&expanded_pattern) {
                pattern.matches_path(path)
            } else {
                path.to_string_lossy().contains(&expanded_pattern)
            }
        })
    }

    // Helper to determine if a file matches a given rule strategy
    fn matches_strategy(&self, entry: &DirEntry, rule: &ScanRule, config: &AppConfig) -> bool {
        let path = entry.path();

        // Basic ignore check
        if self.is_ignored(path, config) {
            return false;
        }

        match &rule.strategy {
            ScanStrategy::Recursive => true, // Already handled by WalkDir
            ScanStrategy::Shallow => entry.depth() <= 1, // Only direct children
            ScanStrategy::Regex(pattern) => {
                if let Ok(re) = Regex::new(pattern) {
                    re.is_match(path.to_string_lossy().as_ref())
                } else {
                    false
                }
            }
            ScanStrategy::OlderThanDays(days) => {
                if let Ok(metadata) = entry.metadata() {
                    if let Ok(modified_time) = metadata.modified() {
                        let modified_datetime: DateTime<Local> = modified_time.into();
                        let age = Local::now() - modified_datetime;
                        age > Duration::days(*days as i64)
                    } else {
                        false
                    }
                } else {
                    false
                }
            }
        }
    }

    // Helper to expand tilde in paths
    fn expand_path(path: &str) -> PathBuf {
        PathBuf::from(shellexpand::tilde(path).to_string())
    }

    // Helper to calculate directory size recursively
    fn calculate_dir_size(path: &Path) -> u64 {
        WalkDir::new(path)
            .into_iter()
            .filter_map(|entry| entry.ok())
            .filter_map(|entry| entry.metadata().ok())
            .filter(|metadata| metadata.is_file())
            .map(|metadata| metadata.len())
            .sum()
    }

    fn move_to_trash(&self, path: &Path) -> Result<PathBuf, String> {
        #[cfg(target_os = "macos")]
        {
            let home = dirs::home_dir().ok_or_else(|| "missing home dir".to_string())?;
            let trash_dir = home.join(".Trash");
            fs::create_dir_all(&trash_dir).map_err(|e| e.to_string())?;
            let file_name = path
                .file_name()
                .ok_or_else(|| "missing file name".to_string())?
                .to_string_lossy()
                .to_string();
            let mut target = trash_dir.join(&file_name);
            if target.exists() {
                let suffix = Uuid::new_v4().to_string();
                target = trash_dir.join(format!("{}.{}", file_name, suffix));
            }
            fs::rename(path, &target).map_err(|e| e.to_string())?;
            Ok(target)
        }

        #[cfg(not(target_os = "macos"))]
        {
            trash::delete(path).map_err(|e| e.to_string())?;
            Ok(path.to_path_buf())
        }
    }
}

#[async_trait]
impl FileSystemPort for OsFileSystemAdapter {
    async fn scan_cleanable_items(
        &self,
        rules: &[ScanRule],
        config: &AppConfig,
    ) -> Result<ScanResult, CoreError> {
        let start = std::time::Instant::now();
        let found_items: Vec<CleanableItem> = rules
            .par_iter()
            .flat_map(|rule| {
                let expanded_path = Self::expand_path(&rule.path_pattern);

                if !expanded_path.exists() {
                    return vec![];
                }

                let mut walker = WalkDir::new(&expanded_path).follow_links(config.follow_symlinks);
                if let Some(max_depth) = config.max_scan_depth {
                    walker = walker.max_depth(max_depth);
                }

                // Filter based on rule strategy and ignore list
                walker
                    .into_iter()
                    .filter_map(|entry_result| entry_result.ok())
                    .filter(|entry| {
                        // Skip directories themselves unless they are the target
                        if entry.file_type().is_dir() && entry.path() != expanded_path {
                            return false;
                        }
                        self.matches_strategy(entry, rule, config)
                    })
                    .filter_map(|entry| {
                        let path = entry.path().to_path_buf();
                        if let Ok(metadata) = entry.metadata() {
                            if metadata.is_file() {
                                let item_id = Uuid::new_v4().to_string();
                                Some(CleanableItem {
                                    rule_id: rule.id.clone(),
                                    id: item_id,
                                    category: rule.category.clone(),
                                    path: path.clone(),
                                    size: metadata.len(),
                                    description: format!(
                                        "{} ({})",
                                        entry.file_name().to_string_lossy(),
                                        rule.name
                                    ),
                                    can_undo: true,
                                    undo_info: None,
                                })
                            } else if metadata.is_dir() && entry.path() == expanded_path {
                                // If the rule targets a directory, include it as a cleanable item
                                let item_id = Uuid::new_v4().to_string();
                                let dir_size = Self::calculate_dir_size(&path);
                                Some(CleanableItem {
                                    rule_id: rule.id.clone(),
                                    id: item_id,
                                    category: rule.category.clone(),
                                    path: path.clone(),
                                    size: dir_size,
                                    description: format!(
                                        "{} directory ({})",
                                        entry.file_name().to_string_lossy(),
                                        rule.name
                                    ),
                                    can_undo: true,
                                    undo_info: None,
                                })
                            } else {
                                None
                            }
                        } else {
                            None
                        }
                    })
                    .collect::<Vec<CleanableItem>>()
            })
            .collect();

        let total_size = found_items.iter().map(|item| item.size).sum();

        let result = ScanResult {
            executed_rules: rules.to_vec(),
            total_size,
            items: found_items,
        };

        let scan_id = Uuid::new_v4().to_string();
        let _ = self.store.save_scan(&scan_id, &result).await;
        self.metrics.incr("scan.items", result.items.len() as u64);
        self.metrics.incr("scan.bytes", result.total_size);
        self.metrics.timing("scan.duration", start.elapsed());

        Ok(result)
    }

    async fn prepare_clean(
        &self,
        items: &[CleanableItem],
    ) -> Result<Vec<CleanableItem>, CoreError> {
        let start = std::time::Instant::now();
        let mut prepared_items = Vec::new();
        for item in items {
            if item.can_undo {
                match self.move_to_trash(&item.path) {
                    Ok(trash_path) => {
                        let prepared = CleanableItem {
                            undo_info: if cfg!(target_os = "macos") {
                                Some(trash_path.to_string_lossy().to_string())
                            } else {
                                #[cfg(all(unix, not(target_os = "macos")))]
                                {
                                    Some(Self::encode_linux_undo_info(&item.id, &item.path))
                                }
                                #[cfg(not(all(unix, not(target_os = "macos"))))]
                                {
                                    Some(item.path.to_string_lossy().to_string())
                                }
                            },
                            ..item.clone()
                        };
                        let record = ItemRecord {
                            item_id: prepared.id.clone(),
                            scan_id: "unknown".to_string(),
                            path: prepared.path.clone(),
                            size: prepared.size,
                            can_undo: prepared.can_undo,
                            undo_info: prepared.undo_info.clone(),
                            deleted: false,
                        };
                        let _ = self.store.save_items(&[record]).await;
                        prepared_items.push(prepared);
                    }
                    Err(e) => {
                        return Err(CoreError::Os {
                            message: format!("trash delete failed: {}", e),
                        });
                    }
                }
            } else {
                // If not undoable, just pass it through for direct deletion
                prepared_items.push(item.clone());
            }
        }
        self.metrics
            .incr("clean.prepare.count", prepared_items.len() as u64);
        self.metrics
            .timing("clean.prepare.duration", start.elapsed());
        Ok(prepared_items)
    }

    async fn clean_items(&self, item_ids: &[String]) -> Result<u64, CoreError> {
        let start = std::time::Instant::now();
        let mut freed_bytes = 0;
        for item_id in item_ids {
            let record = self.store.load_item(item_id).await?;
            let Some(item) = record else {
                continue;
            };
            let mut updated = item.clone();
            if item.can_undo {
                if item.undo_info.is_none() {
                    let trash_path = self
                        .move_to_trash(&item.path)
                        .map_err(|e| CoreError::Os { message: e })?;
                    updated.undo_info = if cfg!(target_os = "macos") {
                        Some(trash_path.to_string_lossy().to_string())
                    } else {
                        #[cfg(all(unix, not(target_os = "macos")))]
                        {
                            Some(Self::encode_linux_undo_info(&item.id, &item.path))
                        }
                        #[cfg(not(all(unix, not(target_os = "macos"))))]
                        {
                            Some(item.path.to_string_lossy().to_string())
                        }
                    };
                }
                freed_bytes += item.size;
            } else if item.path.exists() {
                if item.path.is_dir() {
                    fs::remove_dir_all(&item.path).map_err(|e| CoreError::Os {
                        message: format!("delete dir failed: {}: {}", item.path.display(), e),
                    })?;
                } else {
                    fs::remove_file(&item.path).map_err(|e| CoreError::Os {
                        message: format!("delete file failed: {}: {}", item.path.display(), e),
                    })?;
                }
                freed_bytes += item.size;
            }
            updated.deleted = true;
            self.store.save_items(&[updated]).await?;
        }
        self.metrics.incr("clean.items", item_ids.len() as u64);
        self.metrics.incr("clean.bytes", freed_bytes);
        self.metrics.timing("clean.duration", start.elapsed());
        Ok(freed_bytes)
    }

    async fn undo_clean(&self, items: &[CleanableItem]) -> Result<(), CoreError> {
        let start = std::time::Instant::now();
        #[cfg(target_os = "macos")]
        {
            for item in items {
                if let Some(ref trash_path_str) = item.undo_info {
                    let trash_path = PathBuf::from(trash_path_str);
                    let original_path = &item.path;
                    if !trash_path.exists() {
                        self.metrics.incr("undo.not_found", 1);
                        return Err(CoreError::Os {
                            message: format!("trash item not found for {}", item.id),
                        });
                    }
                    if original_path.exists() {
                        return Err(CoreError::Os {
                            message: format!("target path exists for {}", item.id),
                        });
                    }
                    let trash_dir = trash_path.parent().ok_or_else(|| CoreError::Os {
                        message: "invalid trash path".to_string(),
                    })?;
                    if trash_dir.file_name().is_none() {
                        return Err(CoreError::Os {
                            message: format!("invalid trash path for {}", item.id),
                        });
                    }
                    fs::rename(&trash_path, original_path).map_err(|e| {
                        self.metrics.incr("undo.restore_failed", 1);
                        CoreError::Os {
                            message: e.to_string(),
                        }
                    })?;
                } else {
                    return Err(CoreError::Os {
                        message: format!(
                            "Cannot undo item {} as no undo_info is available.",
                            item.id
                        ),
                    });
                }
            }
            self.metrics.incr("undo.items", items.len() as u64);
            self.metrics.timing("undo.duration", start.elapsed());
            return Ok(());
        }

        #[cfg(all(unix, not(target_os = "macos")))]
        {
            for item in items {
                if let Some(ref undo_info) = item.undo_info {
                    let original_path = Self::decode_linux_undo_original_path(undo_info);
                    let trash_items = trash::os_limited::list().map_err(|e| CoreError::Os {
                        message: format!("trash list failed: {e}"),
                    })?;
                    let mut candidates: Vec<TrashItem> = trash_items
                        .into_iter()
                        .filter(|t| t.original_path == original_path)
                        .collect();
                    if candidates.is_empty() {
                        self.metrics.incr("undo.not_found", 1);
                        return Err(CoreError::Os {
                            message: format!("trash item not found for {}", item.id),
                        });
                    }
                    if candidates.len() > 1 {
                        self.metrics.incr("undo.ambiguous", 1);
                        return Err(CoreError::Os {
                            message: format!(
                                "ambiguous trash candidates for {} (count={})",
                                item.id,
                                candidates.len()
                            ),
                        });
                    }
                    let one = if let Some(one) = candidates.pop() {
                        one
                    } else {
                        self.metrics.incr("undo.not_found", 1);
                        return Err(CoreError::Os {
                            message: format!("trash item not found for {}", item.id),
                        });
                    };
                    trash::os_limited::restore_all(vec![one]).map_err(|e| {
                        self.metrics.incr("undo.restore_failed", 1);
                        CoreError::Os {
                            message: format!("trash restore failed: {e}"),
                        }
                    })?;
                } else {
                    return Err(CoreError::Os {
                        message: format!(
                            "Cannot undo item {} as no undo_info is available.",
                            item.id
                        ),
                    });
                }
            }
            self.metrics.incr("undo.items", items.len() as u64);
            self.metrics.timing("undo.duration", start.elapsed());
            return Ok(());
        }

        #[cfg(not(any(target_os = "macos", all(unix, not(target_os = "macos")))))]
        {
            let _ = items;
            Err(CoreError::Os {
                message: "undo not supported on this OS".to_string(),
            })
        }
    }
}
